import { LookupCategory } from '../models/lookup.model';

export interface LookupData {
  id: number;
  category: LookupCategory;
  name: string;
  nameArabic: string | null;
  code: string | null;
  description: string | null;
  orderId: number;
  isDefault: boolean;
  isActive: boolean;
  parentLookupId: number | null;
}

// Countries
export const COUNTRIES: readonly LookupData[] = [
  {
    category: LookupCategory.COUNTRY,
    code: 'JO',
    description: null,
    id: 1,
    isActive: true,
    isDefault: true,
    name: 'Jordan',
    nameArabic: 'الأردن',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'SA',
    description: null,
    id: 2,
    isActive: true,
    isDefault: false,
    name: 'Saudi Arabia',
    nameArabic: 'السعودية',
    orderId: 2,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'AE',
    description: null,
    id: 3,
    isActive: true,
    isDefault: false,
    name: 'United Arab Emirates',
    nameArabic: 'الإمارات العربية المتحدة',
    orderId: 3,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'KW',
    description: null,
    id: 4,
    isActive: true,
    isDefault: false,
    name: 'Kuwait',
    nameArabic: 'الكويت',
    orderId: 4,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'QA',
    description: null,
    id: 5,
    isActive: true,
    isDefault: false,
    name: 'Qatar',
    nameArabic: 'قطر',
    orderId: 5,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'BH',
    description: null,
    id: 6,
    isActive: true,
    isDefault: false,
    name: 'Bahrain',
    nameArabic: 'البحرين',
    orderId: 6,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'OM',
    description: null,
    id: 7,
    isActive: true,
    isDefault: false,
    name: 'Oman',
    nameArabic: 'عمان',
    orderId: 7,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COUNTRY,
    code: 'EG',
    description: null,
    id: 8,
    isActive: true,
    isDefault: false,
    name: 'Egypt',
    nameArabic: 'مصر',
    orderId: 8,
    parentLookupId: null,
  },
];

// Established Types
export const ESTABLISHED_TYPES: readonly LookupData[] = [
  // Business Types (Existing)
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Limited Liability Company',
    id: 9,
    isActive: true,
    isDefault: true,
    name: 'LLC',
    nameArabic: 'شركة ذات مسؤولية محدودة',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Corporation',
    id: 10,
    isActive: true,
    isDefault: false,
    name: 'Corporation',
    nameArabic: 'شركة مساهمة',
    orderId: 2,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Partnership',
    id: 11,
    isActive: true,
    isDefault: false,
    name: 'Partnership',
    nameArabic: 'شراكة',
    orderId: 3,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Sole Proprietorship',
    id: 12,
    isActive: true,
    isDefault: false,
    name: 'Sole Proprietorship',
    nameArabic: 'مؤسسة فردية',
    orderId: 4,
    parentLookupId: null,
  },
  // Facility Types (New)
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Schools',
    id: 13,
    isActive: true,
    isDefault: false,
    name: 'Schools',
    nameArabic: 'مدارس',
    orderId: 5,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Hospitals',
    id: 14,
    isActive: true,
    isDefault: false,
    name: 'Hospitals',
    nameArabic: 'مستشفيات',
    orderId: 6,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Commercial Complex',
    id: 15,
    isActive: true,
    isDefault: false,
    name: 'Commercial Complex',
    nameArabic: 'مجمع تجاري',
    orderId: 7,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Residential Complex',
    id: 16,
    isActive: true,
    isDefault: false,
    name: 'Residential Complex',
    nameArabic: 'مجمع سكني',
    orderId: 8,
    parentLookupId: null,
  },
  {
    category: LookupCategory.ESTABLISHED_TYPE,
    code: null,
    description: 'Other',
    id: 17,
    isActive: true,
    isDefault: false,
    name: 'Other',
    nameArabic: 'أخرى',
    orderId: 9,
    parentLookupId: null,
  },
];

// Company Roles
export const COMPANY_ROLES: readonly LookupData[] = [
  {
    category: LookupCategory.COMPANY_ROLE,
    code: null,
    description: 'Company administrator with full access',
    id: 18,
    isActive: true,
    isDefault: true,
    name: 'Admin',
    nameArabic: 'مدير',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COMPANY_ROLE,
    code: 'TEAMLEADER',
    description: 'Team leader responsible for team management',
    id: 20,
    isActive: true,
    isDefault: false,
    name: 'Team Leader',
    nameArabic: 'قائد الفريق',
    orderId: 2,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COMPANY_ROLE,
    code: null,
    description: 'Technician role for maintenance work',
    id: 21,
    isActive: true,
    isDefault: false,
    name: 'Technician',
    nameArabic: 'فني',
    orderId: 3,
    parentLookupId: null,
  },
  {
    category: LookupCategory.COMPANY_ROLE,
    code: null,
    description: 'Sub-technician role for assisting technicians',
    id: 22,
    isActive: true,
    isDefault: false,
    name: 'Sub-Technician',
    nameArabic: 'فني مساعد',
    orderId: 4,
    parentLookupId: null,
  },
];

// User Roles
export const USER_ROLES: readonly LookupData[] = [
  {
    category: LookupCategory.USER_ROLE,
    code: 'INDIVIDUAL',
    description: 'Individual user without company affiliation',
    id: 23,
    isActive: true,
    isDefault: false,
    name: 'Individual',
    nameArabic: 'فرد',
    orderId: 5,
    parentLookupId: null,
  },
  {
    category: LookupCategory.USER_ROLE,
    code: 'SUPERADMIN',
    description: 'Super administrator with full system access',
    id: 25,
    isActive: true,
    isDefault: false,
    name: 'Super Admin',
    nameArabic: 'مدير النظام',
    orderId: 6,
    parentLookupId: null,
  },
  {
    category: LookupCategory.USER_ROLE,
    code: 'SUPERUSER',
    description: 'Super user with elevated permissions',
    id: 26,
    isActive: true,
    isDefault: false,
    name: 'Super User',
    nameArabic: 'مستخدم فائق',
    orderId: 7,
    parentLookupId: null,
  },
];

// Team Leaders - REMOVED: Now using USER_ROLE with code 'TEAMLEADER' instead

// Business Models
export const BUSINESS_MODELS: readonly LookupData[] = [
  {
    category: LookupCategory.BUSINESS_MODEL,
    code: null,
    description: 'Business to Business model',
    id: 24,
    isActive: true,
    isDefault: true,
    name: 'B2B',
    nameArabic: 'بين الشركات',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.BUSINESS_MODEL,
    code: null,
    description: 'White Label business model',
    id: 25,
    isActive: true,
    isDefault: false,
    name: 'White Label',
    nameArabic: 'العلامة البيضاء',
    orderId: 2,
    parentLookupId: null,
  },
];

// Managed By
export const MANAGED_BY: readonly LookupData[] = [
  {
    category: LookupCategory.MANAGED_BY,
    code: null,
    description: 'Managed by client team',
    id: 205,
    isActive: true,
    isDefault: false,
    name: 'Client Team',
    nameArabic: 'فريق العميل',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.MANAGED_BY,
    code: null,
    description: 'Managed by WeFix team',
    id: 27,
    isActive: true,
    isDefault: true,
    name: 'WeFix Team',
    nameArabic: 'فريق وي فيكس',
    orderId: 2,
    parentLookupId: null,
  },
];

// Main Services
// Main services have been moved to lookups table with category 'MainService'
// See subServicesSeed.ts for sub services

// Combined lookup data
export const STATES: readonly LookupData[] = [
  {
    category: LookupCategory.STATE,
    code: 'AM',
    description: 'Amman Governorate',
    id: 28,
    isActive: true,
    isDefault: true,
    name: 'Amman',
    nameArabic: 'عمان',
    orderId: 1,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'IR',
    description: 'Irbid Governorate',
    id: 29,
    isActive: true,
    isDefault: false,
    name: 'Irbid',
    nameArabic: 'إربد',
    orderId: 2,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'ZA',
    description: 'Zarqa Governorate',
    id: 30,
    isActive: true,
    isDefault: false,
    name: 'Zarqa',
    nameArabic: 'الزرقاء',
    orderId: 3,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'AQ',
    description: 'Aqaba Governorate',
    id: 31,
    isActive: true,
    isDefault: false,
    name: 'Aqaba',
    nameArabic: 'العقبة',
    orderId: 4,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'BA',
    description: 'Balqa Governorate',
    id: 32,
    isActive: true,
    isDefault: false,
    name: 'Balqa',
    nameArabic: 'البلقاء',
    orderId: 5,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'MA',
    description: 'Mafraq Governorate',
    id: 33,
    isActive: true,
    isDefault: false,
    name: 'Mafraq',
    nameArabic: 'المفرق',
    orderId: 6,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'MD',
    description: 'Madaba Governorate',
    id: 34,
    isActive: true,
    isDefault: false,
    name: 'Madaba',
    nameArabic: 'مادبا',
    orderId: 7,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'JR',
    description: 'Jerash Governorate',
    id: 35,
    isActive: true,
    isDefault: false,
    name: 'Jerash',
    nameArabic: 'جرش',
    orderId: 8,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'AJ',
    description: 'Ajloun Governorate',
    id: 36,
    isActive: true,
    isDefault: false,
    name: 'Ajloun',
    nameArabic: 'عجلون',
    orderId: 9,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'KR',
    description: 'Karak Governorate',
    id: 37,
    isActive: true,
    isDefault: false,
    name: 'Karak',
    nameArabic: 'الكرك',
    orderId: 10,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'TA',
    description: 'Tafilah Governorate',
    id: 38,
    isActive: true,
    isDefault: false,
    name: 'Tafilah',
    nameArabic: 'الطفيلة',
    orderId: 11,
    parentLookupId: 1, // Jordan
  },
  {
    category: LookupCategory.STATE,
    code: 'MN',
    description: "Ma'an Governorate",
    id: 39,
    isActive: true,
    isDefault: false,
    name: "Ma'an",
    nameArabic: 'معان',
    orderId: 12,
    parentLookupId: 1, // Jordan
  },
  // Saudi Arabia States
  {
    category: LookupCategory.STATE,
    code: 'RIY',
    description: 'Riyadh Province',
    id: 40,
    isActive: true,
    isDefault: true,
    name: 'Riyadh',
    nameArabic: 'الرياض',
    orderId: 1,
    parentLookupId: 2, // Saudi Arabia
  },
  {
    category: LookupCategory.STATE,
    code: 'MAK',
    description: 'Makkah Province',
    id: 41,
    isActive: true,
    isDefault: false,
    name: 'Makkah',
    nameArabic: 'مكة المكرمة',
    orderId: 2,
    parentLookupId: 2, // Saudi Arabia
  },
  {
    category: LookupCategory.STATE,
    code: 'MAD',
    description: 'Madinah Province',
    id: 42,
    isActive: true,
    isDefault: false,
    name: 'Madinah',
    nameArabic: 'المدينة المنورة',
    orderId: 3,
    parentLookupId: 2, // Saudi Arabia
  },
  {
    category: LookupCategory.STATE,
    code: 'EAS',
    description: 'Eastern Province',
    id: 43,
    isActive: true,
    isDefault: false,
    name: 'Eastern Province',
    nameArabic: 'المنطقة الشرقية',
    orderId: 4,
    parentLookupId: 2, // Saudi Arabia
  },
  // UAE States (Emirates)
  {
    category: LookupCategory.STATE,
    code: 'DXB',
    description: 'Dubai Emirate',
    id: 44,
    isActive: true,
    isDefault: true,
    name: 'Dubai',
    nameArabic: 'دبي',
    orderId: 1,
    parentLookupId: 3, // UAE
  },
  {
    category: LookupCategory.STATE,
    code: 'AUH',
    description: 'Abu Dhabi Emirate',
    id: 45,
    isActive: true,
    isDefault: false,
    name: 'Abu Dhabi',
    nameArabic: 'أبو ظبي',
    orderId: 2,
    parentLookupId: 3, // UAE
  },
  {
    category: LookupCategory.STATE,
    code: 'SHJ',
    description: 'Sharjah Emirate',
    id: 46,
    isActive: true,
    isDefault: false,
    name: 'Sharjah',
    nameArabic: 'الشارقة',
    orderId: 3,
    parentLookupId: 3, // UAE
  },
  {
    category: LookupCategory.STATE,
    code: 'AJM',
    description: 'Ajman Emirate',
    id: 47,
    isActive: true,
    isDefault: false,
    name: 'Ajman',
    nameArabic: 'عجمان',
    orderId: 4,
    parentLookupId: 3, // UAE
  },
  // Kuwait States (Governorates)
  {
    category: LookupCategory.STATE,
    code: 'KUW',
    description: 'Kuwait City Governorate',
    id: 48,
    isActive: true,
    isDefault: true,
    name: 'Kuwait',
    nameArabic: 'الكويت',
    orderId: 1,
    parentLookupId: 4, // Kuwait
  },
  {
    category: LookupCategory.STATE,
    code: 'AHM',
    description: 'Ahmadi Governorate',
    id: 49,
    isActive: true,
    isDefault: false,
    name: 'Ahmadi',
    nameArabic: 'الأحمدي',
    orderId: 2,
    parentLookupId: 4, // Kuwait
  },
  {
    category: LookupCategory.STATE,
    code: 'HAW',
    description: 'Hawalli Governorate',
    id: 50,
    isActive: true,
    isDefault: false,
    name: 'Hawalli',
    nameArabic: 'حولي',
    orderId: 3,
    parentLookupId: 4, // Kuwait
  },
  // Qatar States (Municipalities)
  {
    category: LookupCategory.STATE,
    code: 'DOH',
    description: 'Doha Municipality',
    id: 51,
    isActive: true,
    isDefault: true,
    name: 'Doha',
    nameArabic: 'الدوحة',
    orderId: 1,
    parentLookupId: 5, // Qatar
  },
  {
    category: LookupCategory.STATE,
    code: 'RAY',
    description: 'Al Rayyan Municipality',
    id: 52,
    isActive: true,
    isDefault: false,
    name: 'Al Rayyan',
    nameArabic: 'الريان',
    orderId: 2,
    parentLookupId: 5, // Qatar
  },
  {
    category: LookupCategory.STATE,
    code: 'WAK',
    description: 'Al Wakrah Municipality',
    id: 53,
    isActive: true,
    isDefault: false,
    name: 'Al Wakrah',
    nameArabic: 'الوكرة',
    orderId: 3,
    parentLookupId: 5, // Qatar
  },
  // Bahrain States (Governorates)
  {
    category: LookupCategory.STATE,
    code: 'MAN',
    description: 'Manama Governorate',
    id: 54,
    isActive: true,
    isDefault: true,
    name: 'Manama',
    nameArabic: 'المنامة',
    orderId: 1,
    parentLookupId: 6, // Bahrain
  },
  {
    category: LookupCategory.STATE,
    code: 'MUH',
    description: 'Muharraq Governorate',
    id: 55,
    isActive: true,
    isDefault: false,
    name: 'Muharraq',
    nameArabic: 'المحرق',
    orderId: 2,
    parentLookupId: 6, // Bahrain
  },
  {
    category: LookupCategory.STATE,
    code: 'NRN',
    description: 'Northern Governorate',
    id: 56,
    isActive: true,
    isDefault: false,
    name: 'Northern',
    nameArabic: 'الشمالية',
    orderId: 3,
    parentLookupId: 6, // Bahrain
  },
  // Oman States (Governorates)
  {
    category: LookupCategory.STATE,
    code: 'MUS',
    description: 'Muscat Governorate',
    id: 57,
    isActive: true,
    isDefault: true,
    name: 'Muscat',
    nameArabic: 'مسقط',
    orderId: 1,
    parentLookupId: 7, // Oman
  },
  {
    category: LookupCategory.STATE,
    code: 'DHA',
    description: 'Dhofar Governorate',
    id: 58,
    isActive: true,
    isDefault: false,
    name: 'Dhofar',
    nameArabic: 'ظفار',
    orderId: 2,
    parentLookupId: 7, // Oman
  },
  {
    category: LookupCategory.STATE,
    code: 'BAT',
    description: 'Al Batinah Governorate',
    id: 59,
    isActive: true,
    isDefault: false,
    name: 'Al Batinah',
    nameArabic: 'الباطنة',
    orderId: 3,
    parentLookupId: 7, // Oman
  },
  // Egypt States (Governorates)
  {
    category: LookupCategory.STATE,
    code: 'CAI',
    description: 'Cairo Governorate',
    id: 60,
    isActive: true,
    isDefault: true,
    name: 'Cairo',
    nameArabic: 'القاهرة',
    orderId: 1,
    parentLookupId: 8, // Egypt
  },
  {
    category: LookupCategory.STATE,
    code: 'ALX',
    description: 'Alexandria Governorate',
    id: 61,
    isActive: true,
    isDefault: false,
    name: 'Alexandria',
    nameArabic: 'الإسكندرية',
    orderId: 2,
    parentLookupId: 8, // Egypt
  },
  {
    category: LookupCategory.STATE,
    code: 'GIZ',
    description: 'Giza Governorate',
    id: 62,
    isActive: true,
    isDefault: false,
    name: 'Giza',
    nameArabic: 'الجيزة',
    orderId: 3,
    parentLookupId: 8, // Egypt
  },
  {
    category: LookupCategory.STATE,
    code: 'SHK',
    description: 'Sharkia Governorate',
    id: 63,
    isActive: true,
    isDefault: false,
    name: 'Sharkia',
    nameArabic: 'الشرقية',
    orderId: 4,
    parentLookupId: 8, // Egypt
  },
];

// Ticket Codes
export const TICKET_CODES: readonly LookupData[] = [
  {
    category: LookupCategory.TICKET_CODE,
    code: 'TKT-001',
    description: 'Standard ticket code',
    id: 200,
    isActive: true,
    isDefault: true,
    name: 'TKT-001',
    nameArabic: 'TKT-001',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TICKET_CODE,
    code: 'TKT-002',
    description: 'Alternative ticket code',
    id: 201,
    isActive: true,
    isDefault: false,
    name: 'TKT-002',
    nameArabic: 'TKT-002',
    orderId: 2,
    parentLookupId: null,
  },
];

// Ticket Types
export const TICKET_TYPES: readonly LookupData[] = [
  {
    category: LookupCategory.TICKET_TYPE,
    code: 'CORR',
    description: 'Corrective maintenance ticket',
    id: 203,
    isActive: true,
    isDefault: true,
    name: 'Corrective',
    nameArabic: 'تصحيحي',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TICKET_TYPE,
    code: 'EMRG',
    description: 'Emergency maintenance ticket',
    id: 204,
    isActive: true,
    isDefault: false,
    name: 'Emergency',
    nameArabic: 'طوارئ',
    orderId: 2,
    parentLookupId: null,
  },
];

// Ticket Statuses
export const TICKET_STATUSES: readonly LookupData[] = [
  {
    category: LookupCategory.TICKET_STATUS,
    code: 'PEND',
    description: 'Ticket is pending',
    id: 109,
    isActive: true,
    isDefault: true,
    name: 'Pending',
    nameArabic: 'قيد الانتظار',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TICKET_STATUS,
    code: 'PROG',
    description: 'Ticket is in progress',
    id: 110,
    isActive: true,
    isDefault: false,
    name: 'In Progress',
    nameArabic: 'قيد التنفيذ',
    orderId: 2,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TICKET_STATUS,
    code: 'COMP',
    description: 'Ticket is completed',
    id: 111,
    isActive: true,
    isDefault: false,
    name: 'Completed',
    nameArabic: 'مكتمل',
    orderId: 3,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TICKET_STATUS,
    code: 'CANC',
    description: 'Ticket is cancelled',
    id: 112,
    isActive: true,
    isDefault: false,
    name: 'Cancelled',
    nameArabic: 'ملغي',
    orderId: 4,
    parentLookupId: null,
  },
];

export const LOOKUP_DATA: readonly LookupData[] = [
  ...BUSINESS_MODELS,
  ...COUNTRIES,
  ...STATES,
  ...ESTABLISHED_TYPES,
  ...MANAGED_BY,
  ...COMPANY_ROLES,
  ...USER_ROLES,
  ...TICKET_CODES,
  ...TICKET_TYPES,
  ...TICKET_STATUSES,
];

